language: r
sudo: required
cache: packages

services:
  - couchdb
  - redis

addons:
  apt:
    packages:
      - libhiredis-dev

r_binary_packages:
  - RcppRedis

r_github_packages:
  - richfitz/redux
  - ropensci/RedisAPI
  - ropensci/rrlite

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: MIahHdXUhj4BLer8KfpDN+PmSzLPak59m2xyBgHvJuHp9RFLpXcOToyE0CF1Lbt8caxlox0FSmuqfqa0s+HrQhYOB6uAcFunDVOGV//MJrkms53LZqCqo2wrvEBastmv4Xv7+e5vBSG+M4bzRdf5MWn8QBTzzPeyJLkuOuu9V20=
